### ISSUE TITLE
launchd crash

### ISSUE THREAD

**Issue by cutecodee** [alephsecurity/xnu-qemu-arm64#17]
I patched launchd (I checked if the patch was applied correctly) and signed it using 'sudo jtool --sign --ent ent_launchd.xml --ident com.apple.xpc.launchd --inplace /Volumes/PeaceB16B92.arm64UpdateRamDisk/sbin/launchd', 'jtool --sig --ent /Volumes/PeaceB16B92.arm64UpdateRamDisk/sbin/launchd', copied the CDHash in the tchashes file and built the trust cache but I got this crash:
https://pastebin.com/S9xqXQ3B
Here is the file I used for entitlements:

[ent_launchd.xml.zip](https://github.com/alephsecurity/xnu-qemu-arm64/files/4457638/ent_launchd.xml.zip)

**Comment by jonyafek** [comment]
It looks like it is trying to boot from the secondary disk image instead of the main one. For now I did a quick dirty hack there with sleep() in the driver code to arrange the order of the 2 disk images but I already have a fix to make it more stable. I will update when the fix is out. In the meanwhile you can try and play with the sleep time value or try to run it again and it might work the second time.
